# passwordSecret: password
# postgresUserPassword: username
# postgresAdminPassword: password
# root-user: username
# root-password: password
# authPublicKey: publicKey
# authPrivateKey: privateKey
# artemisUser: username
# artemisPassword: password
# databaseUser: username
# databasePassword: password
# minioRootUser: password
# minioRootAdmin: admin
# minioAccessKey: admin
# minioSecretKey: password
# mongodbUser: username
# mongodbPassword: password
# docker_hub_username: username
# docker_hub_password: password
