# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: {{ .Values.executionEnvironment.name}}
#   name: {{ .Values.executionEnvironment.name}}
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: {{ .Values.executionEnvironment.name}}
#   type: ClusterIP
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Values.executionEnvironment.name}}
#   labels:
#     app: {{ .Values.executionEnvironment.name}}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: {{ .Values.executionEnvironment.name}}
#   template:
#     metadata:
#       labels:
#         app: {{ .Values.executionEnvironment.name}}
#     spec:
#       containers:
#         - name: {{ .Values.executionEnvironment.name}}
#           image: {{ .Values.executionEnvironment.image }}
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80
#           env:
#             - name: WORKFLOW_LOGS_PATH
#               value: {{ .Values.global.workflow_log_path }}
#             - name: CODE_GENERATOR_EXCHANGE_NAME
#               value: {{ .Values.codeGenerator.exchange_name }}
#             - name: CODE_GENERATOR_ROUTING_KEY
#               value: {{ .Values.codeGenerator.routing_key }}
#             - name: CINCO_DE_BIO_NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#           volumeMounts:
#             - name: shared-volume
#               mountPath: /data
#       volumes:
#         - name: shared-volume
#           persistentVolumeClaim:
#             claimName: {{ .Release.Name }}-workflow-logs-pvc
