apiVersion: v1
kind: Service
metadata:
  labels:
    app: execution-environment
  name: execution-environment
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: execution-environment
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-environment
  labels:
    app: execution-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-environment
  template:
    metadata:
      labels:
        app: execution-environment
    spec:
      containers:
        - name: execution-environment
          image: {{ .Values.executionEnvironment.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: WORKFLOW_LOGS_PATH
              value: {{ .Values.global.workflow_log_path }}
            - name: CODE_GENERATOR_EXCHANGE_NAME
              value: {{ .Values.codeGenerator.exchange_name }}
            - name: CODE_GENERATOR_ROUTING_KEY
              value: {{ .Values.codeGenerator.routing_key }}
          volumeMounts:
            - name: shared-volume
              mountPath: /data
        volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-workflow-logs-pvc