apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"

spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
  rules:
    - host: 
    - http:
        paths:
          - path: /api/(.*)$
            pathType: Prefix
            backend:
              service:
                name: service1
                port:
                  number: 80
          # Definitely needs to be available outside the cluster
          - path: /{{ .Values.global.execution_api_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.executionApi.name }}
                port:
                  number: 80

          - path: /{{ .Values.global.jobs_api_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jobsApi.name }}
                port:
                  number: 80
          # Definitely needs to be available outside the cluster
          - path: /{{ .Values.global.services_api_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceApi.name }}
                port:
                  number: 80
          # Definitely needs to be available outside the cluster
          - path: /{{ .Values.global.minio_console_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.minio.fullnameOverride }}
                port:
                  number: 9001
          # Definitely needs to be available outside the cluster
          - path: /{{ .Values.global.minio_presigned_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginxProxy.name }}
                port:
                  number: 80
          # Definitely needs to be available outside the cluster
          - path: /{{ .Values.global.sib_manager_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.sibManager.name }}
                port:
                  number: 80
          
          - path: /{{ .Values.global.data_manager_ingress_path }}/(.*)$
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dataManager.name }}
                port:
                  number: 80

     
