---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.executionEnvironment.name }}-lb
  labels:
    app: {{ .Values.executionEnvironment.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: {{ .Values.executionEnvironment.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.executionEnvironment.name }}-hl
  labels:
    app: {{ .Values.executionEnvironment.name }}
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: {{ .Values.executionEnvironment.name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.executionEnvironment.name }}
  labels:
    app: {{ .Values.executionEnvironment.name }}
spec:
  serviceName: {{ .Values.executionEnvironment.name }}-hl
  replicas: {{ .Values.executionEnvironment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.executionEnvironment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.executionEnvironment.name }}
    spec:
      containers:
      - name: {{ .Values.executionEnvironment.name }}
        image: {{ .Values.executionEnvironment.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: http
        env:
          - name: WORKFLOW_LOGS_PATH
            value: {{ .Values.global.workflow_log_path }}
          - name: CODE_GENERATOR_EXCHANGE_NAME
            value: {{ .Values.codeGenerator.exchange_name }}
          - name: CODE_GENERATOR_ROUTING_KEY
            value: {{ .Values.codeGenerator.routing_key }}
          - name: CINCO_DE_BIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
            requests:
                memory: "256Mi"
                cpu: "250m"
            limits:
                memory: "1Gi"
                cpu: "1"

{{- if .Values.executionEnvironment.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.executionEnvironment.name }}-hpa
  labels:
    app: {{ .Values.executionEnvironment.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.executionEnvironment.name }}
  minReplicas: {{ .Values.executionEnvironment.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.executionEnvironment.autoscaling.maxReplicas | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.executionEnvironment.autoscaling.targetCPUUtilizationPercentage | default 80 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.executionEnvironment.autoscaling.targetMemoryUtilizationPercentage | default 80 }}
---
{{- end }}


        