apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.frontend.name }}
  name: {{ .Values.frontend.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.frontend.name }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # for verifying the JWT token
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: cinco-cloud-main-secrets
                  key: authPublicKey
            - name: {{ .Values.frontend.name | upper }}_EXT_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.frontend_ingress_path }}
            - name: {{ .Values.sibManager.name | upper }}_EXT_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.sib_manager_ingress_path }}
            - name: {{ .Values.serviceApi.name | upper }}_EXT_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.services_api_ingress_path }}
            - name: {{ .Values.executionApi.name | upper }}_EXT_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.execution_api_ingress_path }}
            - name: {{ .Values.dataManager.name | upper }}_EXT_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.data_manager_ingress_path }}
            - name: SIB_MANAGER_API_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.sib_manager_ingress_path }}
            - name: DATA_MANAGER_API_INGRESS
              value: {{ .Values.global.ingress_paths.data_manager_ingress_path }}
            - name: EXECUTION_API_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.execution_api_ingress_path }}
            - name: SERVICES_API_SERVICE_HOSTNAME
              value: {{ .Values.global.ingress_paths.services_api_ingress_path }}
            - name: CINCO_DE_BIO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace