apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
spec:
  rules:
  - host:
  - http:
      paths:
      - path: /app/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: 80

      # Definitely needs to be available outside the cluster
      - path: /{{ .Values.global.ingress_paths.minio_console_ingress_path }}/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.minio.fullnameOverride }}
            port:
              number: 9001
---
# minio-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-presigned-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host {{ .Values.minio.nameOverride }}.{{ .Values.global.application_namespace }}.svc.cluster.local:9000;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      chunked_transfer_encoding off;
spec:
  rules:
  - host:
  - http:
      paths:
      # Definitely needs to be available outside the cluster
      - path: /{{ .Values.global.ingress_paths.minio_presigned_ingress_path }}/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.minio.fullnameOverride }}
            port:
              number: 9000

# external access to apis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ext/$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
spec:
  rules:
  - host:
  - http:
      paths:
      # Definitely needs to be available outside the cluster
      - path: /{{ .Values.global.ingress_paths.execution_api_ingress_path }}/ext/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.executionApi.name }}
            port:
              number: 80

      - path: /{{ .Values.global.ingress_paths.jobs_api_ingress_path }}/ext/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.jobsApi.name }}
            port:
              number: 80
      # Definitely needs to be available outside the cluster
      - path: /{{ .Values.global.ingress_paths.services_api_ingress_path }}/ext/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceApi.name }}
            port:
              number: 80
      # Definitely needs to be available outside the cluster
      - path: /{{ .Values.global.ingress_paths.sib_manager_ingress_path }}/ext/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.sibManager.name }}
            port:
              number: 80

      - path: /{{ .Values.global.ingress_paths.data_manager_ingress_path }}/ext/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.dataManager.name }}
            port:
              number: 80
