apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.ontologyManager.name }}
  name: {{ .Values.ontologyManager.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.ontologyManager.name }}
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontology-manager-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ontologyManager.name }}
  labels:
    app: {{ .Values.ontologyManager.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ontologyManager.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ontologyManager.name }}
    spec:
      containers:
        - name: {{ .Values.ontologyManager.name }}
          image: {{ .Values.ontologyManager.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ontology-manager-state-volume
              mountPath: /ontology-manager-state
          env:
          - name: CINCO_DE_BIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DEFAULT_ONTOLOGY_URL
            value: {{ .Values.global.ontology.default_url }}
          - name: ONTOLOGY_MANAGER_STATE_PATH
            value: /ontology-manager-state
          - name : DUMMY_VALUE
            value: "dummy"
      volumes:
        - name: ontology-manager-state-volume
          persistentVolumeClaim:
            claimName: ontology-manager-state-pvc