apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.sibManager.name }}
  name: {{ .Values.sibManager.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.sibManager.name }}
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sibManager.kaniko.context_pvc_name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sib-manager-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sibManager.name }}
  labels:
    app: {{ .Values.sibManager.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.sibManager.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.sibManager.name }}
    spec:
      containers:
        - name: {{ .Values.sibManager.name }}
          image: {{ .Values.sibManager.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: docker-context-volume
              mountPath: {{ .Values.sibManager.kaniko.context_pvc_mount_path }}
            - name: sib-manager-state-volume
              mountPath: /sib-manager-state
          env:
          - name: DOCKER_BUILD_CONTEXT_VOLUME
            value: {{ .Values.sibManager.kaniko.context_pvc_name }}
          - name: DOCKER_BUILD_CONTEXT_MOUNT_PATH
            value: {{ .Values.sibManager.kaniko.context_pvc_mount_path }}
          - name: KANIKO_IMAGE
            value: {{ .Values.sibManager.kaniko.image }}
          - name: KANIKO_BUILD_NAMESPACE
            value: {{ .Values.sibManager.kaniko.namespace }}
          - name: REGISTRY_NAME
            value: {{ .Values.global.containers.cluster_image_registry.name }}
          - name: REGISTRY_NAMESPACE
            value: {{ .Values.global.containers.cluster_image_registry.namespace }}
          - name: REGISTRY_PORT
            value: {{ .Values.global.containers.cluster_image_registry.port | quote }}
          - name: CONTAINER_REGISTRY_DOMAIN_ON_HOST
            value: {{ .Values.global.containers.cluster_image_registry.domain_on_host }}
          - name: SERVICE_API_NAME
            value: {{ .Values.serviceApi.name }}
          - name: DOCKER_HUB_NAMESPACE
            value: {{ .Values.global.containers.docker_hub_namespace}}
          - name: SIB_MANAGER_API_INGRESS_PATH
            value: {{ .Values.global.ingress_paths.sib_manager_ingress_path }}
          - name: EXECUTION_API_INGRESS_PATH
            value: {{ .Values.global.ingress_paths.execution_api_ingress_path }}
          - name: DATA_MANAGER_API_INGRESS
            value: {{ .Values.global.ingress_paths.data_manager_ingress_path }}
          - name: CINCO_DE_BIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        

      volumes:
        - name: docker-context-volume
          persistentVolumeClaim:
            claimName: {{ .Values.sibManager.kaniko.context_pvc_name }}
        - name: sib-manager-state-volume
          persistentVolumeClaim:
            claimName: sib-manager-state-pvc