minio:
  # This is is currently the work around for accessing the minio console (ip address is from multipass)
  nameOverride: "minio"
  fullnameOverride: "minio"
  buckets:
    experimentBucket: "experiment-bucket"
    workflowBucket: "workflow-bucket"
    resultsBucket: "results-bucket"
  # move to a secret file;
  auth:
    rootUser: admin
    rootPassword: mypassword
  extraEnvVars:
      # This is the workaround for accessing the minio console - need to resolve (as it depends on the ip address of the multipass VM for microk8s)
      - name: MINIO_BROWSER_REDIRECT_URL
        value: "http://192.168.64.2/minio-console/"

mongodb:
  image: mongo:latest
  workflowdb:
    name: "workflows"
    collection: "flows"
  jobsdb:
    name: "jobsdb"
    collections: "jobs"

nginxProxy:
  image: nginx:latest

jobsApi:
  image: sccecincodebio/jobs-api:latest
  name: jobs-api

executionApi:
  image: sccecincodebio/execution-api:latest
  name: execution-api

serviceApi:
  image: sccecincodebio/service-api:latest
  name: service-api

codeGenerator:
  image: sccecincodebio/code-generator:latest
  name: code-generator
  exchange_name: "code-generator-exchange"
  routing_key: "code-generator"

sibManager:
  image: sccecincodebio/sib-manager:latest
  name: sib-manager
  kaniko:
    image: "gcr.io/kaniko-project/executor:latest"
    namespace: "kaniko-build"
    context_pvc_name: "kaniko-context"
    context_pvc_mount_path: "/docker-build"

executionEnvironment:
  image: sccecincodebio/execution-environment:latest
  name: execution-environment

global:
  ontology_url: "http://"
  dps_registry: "http://"
  docker_hub_namespace: "sccecellmaps"
  workflow_log_path: "data/workflow-logs"
  dps_name_space: "dataprocessing-service-namespace"
  # These are the default values for the cluster image registry with microk8s
  # However these may need to be changed depending on the cluster
  cluster_image_registry:
    name: "registry"
    namespace: "container-registry"
    port: 5000
    domain_on_host: "localhost:32000"
  