name: Build, Test and Push Cellmaps Services to Dockerhub on Trigger
on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              
            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Image
              run: |
                for dockerfile in $(find . -name Dockerfile); do
                    dir_of_image=$(dirname $dockerfile)
                    image_name=$(basename $dir_of_image)
                    image_name=${image_name//\//-}
                    docker_image_name="${image_name//[^a-zA-Z0-9]/-}"
                    if [[ $docker_image_name != "rpy2-base-image" ]]; then  
                    if [[ $docker_image_name == "sib-manager"]]; then
                        echo "Building $docker_image_name"
                        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest $dir_of_image --push
                    fi  
                    fi
                done;

                





