name: Release Cinco De Bio Chart
on:
  push:
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.repository }}
      CHART_PATH: ./charts/cincodebio
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 5

      - name: Configure Git
        run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Helm repositories for dependencies
        run: |
            helm repo add stable https://charts.helm.sh/stable
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo update

      - name: Run chart-releaser    
        uses: helm/chart-releaser-action@v1.6.0
        with:
            charts_dir: $CHART_PATH
        env:
         CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"